# Generated by Django 5.2.1 on 2025-05-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_smart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='mac_address',
            field=models.CharField(default=123, max_length=17, unique=True),
            preserve_default=False,
        ),
    ]
