# Generated by Django 5.2.1 on 2025-05-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_smart', '0002_sensor_mac_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambiente',
            name='localizacao',
            field=models.CharField(max_length=255),
        ),
    ]
